title: Cybersecurity Portfolio
description: Hands-on SOC Analyst (Level 1) projects, DFIR investigations, SIEM case studies, and Threat Intelligence labs.
show_downloads: false   
google_analytics:       
theme: jekyll-theme-hacker
