title: Cybersecurity Portfolio
baseurl: "/cybersecurity-portfolio"
repository: "https://github.com/youssefmkd/cybersecurity-portfolio"
description: Hands-on SOC Analyst (Level 1) projects, DFIR investigations, SIEM case studies, and Threat Intelligence labs.
show_downloads: false   
google_analytics:       
theme: jekyll-theme-hacker
nav:
  - Home: index.md
  - SOC Level 1: SOC-Level-1-THM/README.md
  - SIEM: SIEM/README.md
social:
  github: "youssefmkd"
  linkedin: "youssef-moukadem"
