title: "Youssef Moukadem | Cybersecurity Portfolio"
baseurl: "/cybersecurity-portfolio"
repository: "https://github.com/youssefmkd/cybersecurity-portfolio"
description: "Cybersecurity Enthusiast | Computer Science Graduate | Cloud Enthusiast | Lifelong Learner"
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker

social_links:
  linkedin: "www.linkedin.com/in/youssef-moukadem"
  tryhackme: "https://tryhackme.com/p/YoussefMoukadem"
  email: "mailto:y.moukadem@outlook.com"
  
